#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CompetitorTool.Resource", IsApplication=true)]

namespace CompetitorTool
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_top = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_bottom = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int buttonSendRequest = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Help = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int send_email = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000c
			public const int LL = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int autocomplete_codes = 2131165197;
			
			// aapt resource value: 0x7f070005
			public const int btnHelpClose = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int btnSend = 2131165195;
			
			// aapt resource value: 0x7f070011
			public const int btnSendFromMain = 2131165201;
			
			// aapt resource value: 0x7f07000a
			public const int editComment = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int editEmail = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int editFIO = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int editOrganization = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int editPhone = 2131165193;
			
			// aapt resource value: 0x7f07000f
			public const int frameLayout1 = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int imageButton1 = 2131165198;
			
			// aapt resource value: 0x7f070001
			public const int imageView1 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int imageView2 = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout2 = 2131165186;
			
			// aapt resource value: 0x7f070012
			public const int results1 = 2131165202;
			
			// aapt resource value: 0x7f070004
			public const int textView1 = 2131165188;
			
			// aapt resource value: 0x7f070010
			public const int textView2 = 2131165200;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionBar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int background = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int cell = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int find = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int finded = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int help = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int listItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int logoBackground = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int mailForm = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int MyActionBarTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int MyCustomTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int codes = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
